config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: %i[new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_categories
  has_many :categories, through: :article_categories
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true,
                       length: { minimum: 6 }, confirmation: { case_sensitive: false }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'You have created an article successfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'You have updated this article successfully'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:warning] = 'You can only edit or delete your own article!'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update]
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'You created a new category successfully'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:success] = 'You updated category name successfully'
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def require_admin
    unless (logged_in? && current_user.admin?)
      flash[:warning] = 'You do not have permission to create a new category'
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:danger] = 'There was something wrong with your login details'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_user, only: %i[edit update destroy]
  before_action :require_same_user, only: %i[edit update]
  before_action :require_same_or_admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Travel Blog #{@user.username}. You created your account successfully"
      redirect_to @user
    else
      render 'users/new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'You updated your account successfully'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session.delete(:user_id) if @user == current_user
    flash[:success] = 'You have deleted your account with articles'
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def require_same_user
    if current_user != @user
      flash[:warning] = 'You can only edit your own account!'
      redirect_to @user
    end
  end

  def require_same_or_admin_user
    if current_user != @user && !current_user.admin?
      flash[:warning] = 'You can only delete your own account!'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 180 })
    email_address = user.email
    size = options[:size]
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:warning] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container mt-4">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center mb-5">
      <div class="col-8">
        <div class="card text-center shadow bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              By <%= link_to(article.user.username, article.user)%>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%=link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', object: @article %>
      <%= form_with model: @article, class:'shadow p-3 mb-5 bg-info text-white,', local: true do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: 'Description' %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.collection_select :category_ids, Category.all, :id, :name, { :prompt => 'Please select categories (can be empty)' }, { :multiple => true, class: "custom-select shadow rounded", size: 3 } %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= link_to 'Return article list', articles_path, class: "btn btn-secondary btn-lg mr-5" %>
          <%= f.submit(f.object.new_record? ? "Create article" : "Update article", class: "btn btn-success btn-lg") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="text-center mt-2">Update article</h1>
</div>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<%= render "articles" %>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="text-center mt-2">Create a new article</h1>
</div>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container mt-4">
  <div class="row justify-content-md-center mb-5">
    <div class="col-8">
      <div class="card text-center shadow bg-white rounded">
        <div class="card-header font-italic">
          By <%= @article.user&.username %>
          <%= link_to gravatar_for(@article.user, size: 100), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-success mr-1"><%= link_to category.name, category, class: "text-light" %></span>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', object: @category %>
      <%= form_with model: @category, class:'shadow p-3 mb-5 bg-info text-white,', local: true do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter category title" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= link_to 'Return article list', articles_path, class: "btn btn-secondary btn-lg mr-5" %>
          <%= f.submit f.object.new_record? ? 'Create category' : 'Update category', class: "btn btn-success btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit category name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="container mt-4">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center mb-5">
      <div class="col-4">
        <div class="card text-center shadow bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%=link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, 'article' ) %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center">Create a new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
  <h1 class="text-center mt-4"><%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %></h1>
<% end %>
<h3 class="text-center mt-4 mb-4">Articles</h3>
<%= render "articles/articles" %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
  <div class="container">
    <span class="text-muted">&copy; Copyright 2021 Travel Blog</span>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Travel Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create a new category", new_category_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", current_user, class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure you want to delete your profile?" } %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page of travel blog.</h1>
<%= link_to 'Articles listing page', articles_path %>|
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container mt-3">
  <div class="jumbotron text-center">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The process in <%= object.class.name.downcase %> form has some errors:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', object: @user %>
      <%= form_with model: @user, class:'shadow p-3 mb-5 bg-info text-white,', local: true do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: 'Enter your email' %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: 'Enter your password' %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password_confirmation, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.password_field :password_confirmation, class: "form-control shadow rounded", placeholder: 'Enter your password again' %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= link_to 'Return article list', articles_path, class: "btn btn-secondary btn-lg mr-5" %>
          <%= f.submit(f.object.new_record? ? "Create account" : "Update account", class: "btn btn-success btn-lg") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Update account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Travel Bloggers</h1>
<div class="container mt-4">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center mb-5">
      <div class="col-8">
        <div class="card text-center shadow bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user%>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to gravatar_for(user, size: 130), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, 'article' ) %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete profile", user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure you want to delete this profile?" } %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %></h1>
<%= gravatar_for @user %>
<% if logged_in? && @user == current_user %>
  <h1 class="text-center mt-4"><%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-outline-info" %></h1>
<% end %>
<h3 class="text-center mt-4 mb-4">Articles</h3>
<%= render "articles/articles" %>